---
printWidth: 90
tabWidth: 2
trailingComma: 'es5'
singleQuote: true
jsxBracketSameLine: true
arrowParens: 'always'
endOfLine: 'lf'
overriders:
  - files:
      - '*.json'
      - '*.py'
    options:
      tabWidth: 4
