language: node_js
cache: npm
git:
  quiet: true
branches:
  only:
  - master
  - develop
install:
  - npm ci
script:
  - npm run build
deploy:
  name: Alexandre Barone
  email: abalexandrebarone@gmail.com
  github_token: $github:YourAngel45:token
  provider: pages
  local_dir: build
  target_branch: gh-pages
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
