language: node_js
node_js:
  - "10"
cache: npm
git:
  quiet: true
branches:
  only:
  - master
install:
  - npm ci
script:
  - npm run build
deploy:
  name: Alexandre Barone
  email: abalexandrebarone@gmail.com
  github_token: $github_yourangel45_token
  provider: pages
  local_dir: build
  target_branch: gh-pages
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
